# Generated by Django 4.2.1 on 2023-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('urls', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='DataCollection',
        ),
    ]
