# Generated by Django 4.2.1 on 2023-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0002_datacollectionurls_delete_datacollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectionurls',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
