# Generated by Django 4.2.1 on 2023-05-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0003_datacollectionurls_updated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalaiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('user', models.IntegerField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
