# Generated by Django 4.2.1 on 2023-06-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0004_personalaikeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('PersonalaiKey', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
