# Generated by Django 4.2.1 on 2023-06-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0005_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('urls', models.CharField(max_length=10000)),
                ('price', models.IntegerField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
