# Generated by Django 4.2.1 on 2023-06-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0006_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.IntegerField()),
                ('weatherjson', models.CharField(max_length=10000)),
            ],
        ),
    ]
