# Generated by Django 4.2.1 on 2023-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0007_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectionurls',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
