# Generated by Django 4.2.1 on 2023-06-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0008_datacollectionurls_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='name',
            new_name='query',
        ),
    ]
