# Generated by Django 4.2.1 on 2023-07-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrainapp', '0009_rename_name_packages_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='urls',
        ),
    ]
